### ISSUE TITLE
fn is not a function. (In 'fn()', 'fn' is undefined)

### ISSUE THREAD

**Issue by inzerceubytovani** [shlomiassaf/ngx-modialog#239]
In your file angular2-modal/providers/outside-event-plugin.js - line 79 - 83 - 
`return zone.runOutsideAngular(function () {
            var fn;
            setTimeout(function () { return fn = onceOnOutside(); }, 0);
            return function () { return fn(); };
        });`

Error I got: `fn is not a function. (In 'fn()', 'fn' is undefined)`

My application gives me error fn is not function. That timeout in some cases when I change some variable quickly from undefined to some value gives me that error when I use this variable in template in negative condition : *ngIf="!myFastChangedVariable". When I remove that setTimeout function, error dissapear. It looks like similar problem like error message "Expression has changed after it was checked" but this error message does not appear.

**Comment by kanitkarIndex** [comment]
I am also having this issue. Have any solutions been found?
