### ISSUE TITLE
how to dismiss all open modals?

### ISSUE THREAD

**Issue by eviljoe** [shlomiassaf/ngx-modialog#314]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
feature... maybe.

* **What is the current behavior?**
I cannot find a way to close all open modals.

* **What is the expected behavior?**
In ui-bootstrap for AngularJS 1, I was able to dismiss all modals using the `dismissAll` function on the `$uibModalStack` service.

* **What is the motivation / use case for changing the behavior?**
When the route changes, I would like to dismiss all open modals.  If I don't do this, the modals will stay open and the route will change behind the modal.

* **Please tell us about your environment:**
  - angluar2-modal version: 2.0.3
  - Angular version: 2.3.1
  - Browser: [ all ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
It would be nice to have a service that I can inject that will give me access to all open modals.  It could even have a convenience method for `dismissAll`.  I see that there is already a `DialogRefStack` class.  It would be enough to just be able to access an instance of that class using the public API.

**Comment by mikevanilla** [comment]
Any update on this problem?

**Comment by pramod-kumar-czone** [comment]
Same need here.Close all cascading modal programmatically.

**Comment by kadosh1000** [comment]
@shlomiassaf 
Any updated on this issue? It's been over 5 months. even a workaround we can use for now would be great

**Comment by shlomiassaf** [comment]
implemented, version 4.0.0-beat.3 / 3.0.4

See demo (bootstrap / vex) for [implementation](https://github.com/shlomiassaf/ngx-modialog/blob/master/src/demo/app/bootstrap-demo/presets.ts#L78-L79)
