### ISSUE TITLE
Inject component into modal

### ISSUE THREAD

**Issue by maximelafarie** [shlomiassaf/ngx-modialog#321]
I'm using the quickstart example method to open a new Modal (it works well):
```
onClick() {
    this.modal.alert()
      .size('lg')
      .showClose(true)
      .title('A simple Alert style modal window')
      .body(`
            <h4>Alert is a classic (title/body/footer) 1 button modal window that 
            does not block.</h4>
            <b>Configuration:</b>
            <ul>
                <li>Non blocking (click anywhere outside to dismiss)</li>
                <li>Size large</li>
                <li>Dismissed with default keyboard key (ESC)</li>
                <li>Close wth button click</li>
                <li>HTML content</li>
            </ul>`)
      .open();
  }
```

I have another component that I want to include into the modal body, `<app-mycmpnt></app-mycmpnt>`.

So I'm trying to do the following : 
```
onClick() {
    this.modal.alert()
      .size('lg')
      .showClose(true)
      .title('A simple Alert style modal window')
      .body(`<app-mycmpnt></app-mycmpnt>`)
      .open();
  }
```
But I'm getting the following error :
`WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).`

I didn't find anything that explain how to do that, given that the `<app-mycmpnt></app-mycmpnt>` only contains HTML for the moment.

**Comment by Dsummers91** [comment]
@maximelafarie  Have you tried calling the component directly: 
`this.modal.open(AppMyComponent, overlayConfigFactory({ isBlocking: false }, BSModalContext));`

(considering app-mycompnt = AppMyComponent. Or whatever naming convention you used.)

BSModalContext is imported from 'angular2-modal/plugins/bootstrap'

You have to include AppMyComponent as an entrycomponent in your module"
```
@NgModule({
  imports:  [],
  declarations [AppMyComponent],
  entryComponents: [AppMyComponent]
```
