### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by achimha** [shlomiassaf/ngx-modialog#343]
Last update was in January 2017. A few important PRs are waiting. Is the project still alive? Should it be forked and submitted to npm under a more appropriate name (although ng-modal, ngx-modal and angular-modal are all taken)?

**Comment by shlomiassaf** [comment]
It is still alive I just have limited time.

I would love to get cooperation from someone who wants to become a maintainer.

Some experience is required of course
