### ISSUE TITLE
Main concepts of this package

### ISSUE THREAD

**Issue by phaeton2040** [shlomiassaf/ngx-modialog#349]
I'm sorry for posting an offtopic question but it would be great if you could help me. In my project I need to create a service which would work like yours but would have much smaller amount of settings and customizations. Could you reply with basic steps of reproducing such service?

**Comment by shlomiassaf** [comment]
@phaeton2040 sorry for the delay...

I won't be able to cover this in an issue. The issues are also not intended for support questions.

You can follow the code and extract the pieces you need.

The basic concepts (for a straight forward, dead simple, implementation using components only):

Use need to use a `ComponentFactoryResolver` so you can obtain a `ComponentFactory` instance for the component you want to render, each `Component` has it's own `ComponentFactory` instance.

The `ComponentFactory` instance is used by a view, the view renders the component within in.

The view can be obtained by injecting a `ViewContainerRef` within a component (e.g a page component, root component etc...)

Each component has a `ViewContainerRef`.

You can see this in action [here](https://github.com/shlomiassaf/ngx-modialog/blob/master/src/ngx-modialog/src/framework/createComponent.ts#L16-L31) (abstracted)

I'm believe that this will lead to more questions about injectorts, getting a default view, view structure etc... please try to find the answers in the code itself, blog posts or the official angular gitter channel.
