### ISSUE TITLE
defaultViewContainer no longer exists

### ISSUE THREAD

**Issue by rolandoldengarm** [shlomiassaf/ngx-modialog#375]
IMPORTANT: Please provide a sample using:  

  * V1: http://plnkr.co/edit/hwbmF9?p=preview 
  * V2: http://plnkr.co/edit/7c0pGE?p=preview

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
BUG

https://github.com/shlomiassaf/angular2-modal/blob/master/QUICKTHROUGH.md

The property `defaultViewContainer` no longer exists in the latest version. However, I still get the error that I need to set this....

**Comment by ashfaqch** [comment]
I am also looking for sample code with latest release 3.0.1

Thanks

**Comment by WeekendMan** [comment]
Got the same issue.
Author, I'm sorry, but maybe you should test the things that you're creating?

**Comment by shlomiassaf** [comment]
Hi,

The source code has no reference to `defaultViewContainer` and I didn't find any error, warning or info that is thrown/showed due to such state.

Also, the demo app does not set the default view container (it cant...) and no error there...

Can you please provide more info?

**Comment by rolandoldengarm** [comment]
@shlomiassaf the QUICKTHROUGH has been removed, and can't reproduce the error anymore.
See this [plunkr](http://plnkr.co/edit/hwbmF9?p=preview), the reference used to be there:

![image](https://user-images.githubusercontent.com/14539000/29290722-431cb784-8195-11e7-9b3f-08c6c3ac038d.png)

Guess it's no longer required in the latest version. Closing.

**Comment by qwe852147** [comment]
Have the same problem , without defaultViewContainer, I get  ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked error.

**Comment by qazq** [comment]
Got the same issue.
