### ISSUE TITLE
AOT error

### ISSUE THREAD

**Issue by AlexSpirin1990** [shlomiassaf/ngx-modialog#377]
I have aot error: 
/node_modules/angular2-modal/plugins/bootstrap/src/angular2-modal-bootstrap.ng-flat.ngfactory.ts:17:35: Namespace ''*'' has no exported member 'BootstrapModalModule'.
/node_modules/angular2-modal/plugins/bootstrap/src/angular2-modal-bootstrap.ng-flat.ngfactory.ts:20:21: Namespace ''*'' has no exported member 'Modal'.
/angular2-modal/plugins/bootstrap/src/angular2-modal-bootstrap.ng-flat.ngfactory.ts:293:20: Namespace ''*'' has no exported member 'BSMessageModalTitle'.
....
How can I fix it ?

**Comment by shlomiassaf** [comment]
I can't help here.

Please reopen a new issue with information about the version of the library, angular version and other information you might think will help understanding the problem.

**Comment by animator013** [comment]
I had also this issue. Upgrading to angular 4.2.6 solved it for me.
