### ISSUE TITLE
Error in walkthrough

### ISSUE THREAD

**Issue by millerf** [shlomiassaf/ngx-modialog#378]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Error in walkthrough.
I just tried to make a simple example and I get an error on this line:

```
export class AppComponent {
  constructor(overlay: Overlay, vcRef: ViewContainerRef, public modal: Modal) {
    overlay.defaultViewContainer = vcRef;
  }
...
}
```

property 'defaultViewContainer' does not exist on type Overlay.

I am using it in ES6 with Angular 4.

It is possible the Overlay has changed since the NG4 update and walkthrough isn't up-to-date?

Thanks.

**Comment by millerf** [comment]
Now getting some serious bugs in Ionic at compile time... Not sure what it is linked to though...
```

09:40:20]  ionic-app-script task: "build" 
[09:40:20]  Error: ./src/app/app.module.ngfactory.js Module not found: Error: Can't resolve 
            '../../angular2-modal/plugins/bootstrap' in '/Users/xxxxx/Documents/www/XXXX/mzk_app/src/app' resolve 
            '../../angular2-modal/plugins/bootstrap' in '/Users/xxxxx/Documents/www/XXXX/mzk_app/src/app' using 
            description file: /Users/xxxxx/Documents/www/XXXXX/mzk_app/package.json (relative path:

```

**Comment by shlomiassaf** [comment]
Walkthrough haw been removed, the quick start is now in the README.

As for the other error, please open a new issue.
