### ISSUE TITLE
Use multiple input fields in dialog

### ISSUE THREAD

**Issue by lexon0011** [shlomiassaf/ngx-modialog#390]
I use angular2-modal@3.0.2. Is there a way to use multiple input fields in a dialog? I need it for some user inputs.  Like this:

```
.body(`
   <h1>Test</h1>
   <input type="text" name="test1" [(ngModel)]="testInput" />
   <input type="text" name="test2" [(ngModel)]="testInput" />
`)
```

I found only a way to use one input field.

Thanks!

**Comment by shlomiassaf** [comment]
Yes, you need to use a custom component.

The library provides a small set of common scenarios like alert, prompt and confirm and that's it, anything else should be done via a custom component.

You want multiple input, then someone else wants 3 inputs  1 checkbox and 2 radio buttons... its endless...

**Comment by lexon0011** [comment]
I try the custom component with the angular2-modal@3.0.2. I use for trying [this demo](https://github.com/shlomiassaf/ngx-modialog/blob/master/src/demo/app/bootstrap-demo/bootstrap-demo-page/custom-modal-sample.ts). I insert the component in the html template (`<modal-content></modal-content>`) and register the component in the module declaration. 

But now I get the following error: `Error: No provider for DialogRef!`

Is there something else to do?

Thanks!

**Comment by shlomiassaf** [comment]
See this demo, v 3.0.3

http://plnkr.co/edit/2ppVYl517GI1Byv8vVbG?p=preview

**Comment by lexon0011** [comment]
I  extend your demo with a custom dialog. Now I get the following error:

`Unhandled Promise rejection: No provider for t!`

I thing it is the same error, but because of uglifying the output is "t" instead of "DialogRef"

You find the updated sample here:  [http://plnkr.co/edit/IIs2E1jgV0nILeLzkMAV](http://plnkr.co/edit/IIs2E1jgV0nILeLzkMAV)

**Comment by lexon0011** [comment]
Could you reproduce the error?

**Comment by lexon0011** [comment]
Is there already a solution? Is it reproducable? I would be very grateful for your help!
