### ISSUE TITLE
Version 3.0.3 is empty and not working

### ISSUE THREAD

**Issue by almothafar** [shlomiassaf/ngx-modialog#391]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When I do install the latest version (3.0.3) I get repository downloaded inside node_module without .js or .d.ts files, but when I install 3.0.2 everything is OK again, I think the 3.0.3 build is broken somehow.

* **Please tell us about your environment:**

- Angular version: 4.3.6
- npm: 5.3.0

**Comment by shlomiassaf** [comment]
@almothafar I just installed it fresh from npm:

This is what is see in `ngx-modialog` directory:

![image](https://user-images.githubusercontent.com/5377501/29844416-dcbe660c-8d17-11e7-9aaf-749b92de08bf.png)

Also, [plunker with v3.0.3](http://plnkr.co/edit/2ppVYl517GI1Byv8vVbG?p=preview) is working fine, although using UMD bundle...

**Comment by almothafar** [comment]
I'm with webpack project using: https://github.com/AngularClass/angular-starter 
I did `npm prune --force && npm i` and for 3.0.3 it was not getting me the files, but for 3.0.2 is working, tried 2 times and failed.

**Comment by shlomiassaf** [comment]
See this [issue-comment](https://github.com/shlomiassaf/ngx-modialog/issues/384#issuecomment-324843550) from another dev confirming version 3.0.3 works.

I'm not sure it's related to the inline template thing, try posting the error message

**Comment by almothafar** [comment]
I'm still not sure about 3.0.3 but got 3.0.4 and it is OK  👍
