### ISSUE TITLE
TS2307: Cannot find module ngx-modialog/plugins/bootstrap

### ISSUE THREAD

**Issue by celestale** [shlomiassaf/ngx-modialog#403]
angular app ng-version=**4.4.4**
typescript=**2.5.3**
ngx-modialog= "_id": "ngx-modialog@**3.0.4**" `(installed with npm install ngx-modial)`

First, I installed ngx-modialog with `npm install ngx-modial`, then went to `app.module.ts` to imports as shown in Quick Start. Is there any steps i missed out? The at-loader is complaining about this error, appreciate your help guys!
```
import { ModalModule } from 'ngx-modialog';
import { BootstrapModalModule } from 'ngx-modialog/plugins/bootstrap';
```
Error:
```
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app/app.module.ts:67:38
    TS2307: Cannot find module 'ngx-modialog/plugins/bootstrap'.
```

**Comment by celestale** [comment]
**UPDATE:** I also tried to create an empty angular project using `angular-cli` with the same error.

**Comment by achimha** [comment]
Try going back to TypeScript 2.5.1.

**Comment by wgsl2005** [comment]
@celestale did rolling back to 2.5.1 solve the issue? I had the same issue. I would appreciate if you can confirm.

**Comment by wgsl2005** [comment]
Just tried. rolling back to 2.5.2 didn't work for me. Any idea?

**Comment by celestale** [comment]
Rolling back to 2.5.1 fixed this issue. But there is no styling on the model. I think I have to `npm install bootstrap` in order to see bootstrap theme?

**Comment by wgsl2005** [comment]
@celestale thank you sir. it turned out I had a wrong reference path - stupid me!. But I did have no styling issue and installing and adding the bootstrap css solved the issue.
