### ISSUE TITLE
Getting data from the modal component

### ISSUE THREAD

**Issue by kevintanhongann** [shlomiassaf/ngx-modialog#411]
I can't wrap my head around how to get data from a custom modal component that was triggered from a component.

Are there any concrete examples on how I can do this? 

Thanks.

**Comment by GerritK** [comment]
You can send a result with `dialog.close(result)`.
If you want to send data without closing the modal I would add an `EventEmitter` to the modal context and emitting data like you would do with an `@Output()`.

**Comment by kevintanhongann** [comment]
Okay cool. Thanks for the quick response. You've helped me out.
